"""
Fraud Detection Dashboard - UI DEMO WITH SYNTHETIC DATA.

Every number this module serves is generated by `random`. It does not call the
fraud detection API and reflects nothing about a running system: the
"transactions per second", "average latency" and risk breakdowns are invented
per tick.

It exists to exercise the WebSocket layout and styling. Do not deploy it as
monitoring - a dashboard that reports healthy traffic while the backend is down
is worse than no dashboard, because it is believed.

For real numbers use GET /api/v1/analytics/dashboard-data, or the Streamlit app
in dashboard/streamlit_app.py which reads it.
"""

from fastapi import FastAPI, WebSocket, WebSocketDisconnect, Request
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from fastapi.responses import HTMLResponse
from typing import List, Dict, Any
import asyncio
import json
import random
from datetime import datetime

app = FastAPI(
    title="Fraud Detection Dashboard (DEMO - synthetic data)",
    description="UI demo. All figures are randomly generated and reflect no real system.",
    version="2.9.0"
)

# Mount static files
app.mount("/static", StaticFiles(directory="dashboard/static"), name="static")

# Templates
templates = Jinja2Templates(directory="dashboard/templates")


class ConnectionManager:
    """Manages WebSocket connections for real-time updates."""
    
    def __init__(self):
        self.active_connections: List[WebSocket] = []
    
    async def connect(self, websocket: WebSocket):
        await websocket.accept()
        self.active_connections.append(websocket)
    
    def disconnect(self, websocket: WebSocket):
        self.active_connections.remove(websocket)
    
    async def broadcast(self, message: Dict[str, Any]):
        for connection in self.active_connections:
            try:
                await connection.send_json(message)
            except:
                pass


manager = ConnectionManager()


@app.get("/", response_class=HTMLResponse)
async def dashboard_home(request: Request):
    """Render the main dashboard page."""
    return templates.TemplateResponse("index.html", {"request": request})


@app.get("/api/stats/realtime")
async def get_realtime_stats():
    """Get real-time fraud detection statistics."""
    # In production, this would come from the analytics module
    return {
        "timestamp": datetime.utcnow().isoformat(),
        "transactions_per_second": random.randint(80, 120),
        "fraud_detected": random.randint(1, 5),
        "avg_latency_ms": round(random.uniform(0.3, 0.8), 2),
        "risk_distribution": {
            "low": random.randint(70, 85),
            "medium": random.randint(10, 20),
            "high": random.randint(3, 8),
            "critical": random.randint(0, 2),
        },
        "top_risk_factors": [
            {"factor": "Unknown Device", "count": random.randint(10, 30)},
            {"factor": "Unusual Location", "count": random.randint(5, 20)},
            {"factor": "High Amount", "count": random.randint(3, 15)},
            {"factor": "Late Night", "count": random.randint(2, 10)},
        ],
    }


@app.get("/api/stats/model-performance")
async def get_model_performance():
    """Get ML model performance metrics."""
    return {
        "models": [
            {
                "name": "XGBoost",
                "accuracy": 0.9987,
                "precision": 0.9892,
                "recall": 0.9756,
                "f1_score": 0.9823,
                "avg_latency_ms": 0.12,
            },
            {
                "name": "LightGBM",
                "accuracy": 0.9982,
                "precision": 0.9878,
                "recall": 0.9712,
                "f1_score": 0.9794,
                "avg_latency_ms": 0.08,
            },
            {
                "name": "CatBoost",
                "accuracy": 0.9979,
                "precision": 0.9865,
                "recall": 0.9698,
                "f1_score": 0.9781,
                "avg_latency_ms": 0.15,
            },
        ],
        "ensemble": {
            "accuracy": 0.9997,
            "precision": 0.9945,
            "recall": 0.9834,
            "f1_score": 0.9889,
        },
    }


@app.get("/api/stats/geographic")
async def get_geographic_stats():
    """Get geographic fraud distribution."""
    return {
        "regions": [
            {"region": "North America", "transactions": 45000, "fraud_rate": 0.012},
            {"region": "Europe", "transactions": 38000, "fraud_rate": 0.009},
            {"region": "Asia Pacific", "transactions": 52000, "fraud_rate": 0.015},
            {"region": "Latin America", "transactions": 12000, "fraud_rate": 0.021},
            {"region": "Middle East", "transactions": 8000, "fraud_rate": 0.018},
        ],
        "hotspots": [
            {"city": "Lagos", "risk_level": "high", "fraud_count": 156},
            {"city": "Moscow", "risk_level": "high", "fraud_count": 134},
            {"city": "Jakarta", "risk_level": "medium", "fraud_count": 98},
        ],
    }


@app.websocket("/ws/transactions")
async def websocket_transactions(websocket: WebSocket):
    """WebSocket endpoint for real-time transaction stream."""
    await manager.connect(websocket)
    try:
        while True:
            # Simulate real-time transaction data
            transaction = {
                "id": f"txn_{random.randint(100000, 999999)}",
                "timestamp": datetime.utcnow().isoformat(),
                "amount": round(random.uniform(10, 5000), 2),
                "risk_score": round(random.uniform(0, 100), 1),
                "risk_level": random.choice(["low", "low", "low", "medium", "high"]),
                "decision": random.choice(["approve", "approve", "approve", "review", "deny"]),
                "location": random.choice(["New York", "London", "Tokyo", "Sydney", "Mumbai"]),
                "device_known": random.choice([True, True, True, False]),
            }
            await websocket.send_json(transaction)
            await asyncio.sleep(0.5)  # Send update every 500ms
    except WebSocketDisconnect:
        manager.disconnect(websocket)


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8080)
